arbcall"void acb_init(acb_t x)"
arbcall"void acb_clear(acb_t x)"
arbcall"void acb_set(acb_t z, const acb_t x)"
arbcall"void acb_set_ui(acb_t z, ulong x)"
arbcall"void acb_set_si(acb_t z, slong x)"
arbcall"void acb_set_d(acb_t z, double x)"
arbcall"void acb_set_arb(acb_t z, const arb_t c)"
arbcall"void acb_set_si_si(acb_t z, slong x, slong y)"
arbcall"void acb_set_d_d(acb_t z, double x, double y)"
arbcall"void acb_set_arb_arb(acb_t z, const arb_t x, const arb_t y)"
arbcall"void acb_const_pi(acb_t y, slong prec)"
