arbcall"void _acb_vec_zero(acb_ptr A, slong n)"
arbcall"int _acb_vec_is_zero(acb_srcptr vec, slong len)"
arbcall"int _acb_vec_is_real(acb_srcptr v, slong len)"
arbcall"void _acb_vec_set(acb_ptr res, acb_srcptr vec, slong len)"
arbcall"void _acb_vec_set_round(acb_ptr res, acb_srcptr vec, slong len, slong prec)"
arbcall"void _acb_vec_neg(acb_ptr res, acb_srcptr vec, slong len)"
arbcall"void _acb_vec_add(acb_ptr res, acb_srcptr vec1, acb_srcptr vec2, slong len, slong prec)"
arbcall"void _acb_vec_sub(acb_ptr res, acb_srcptr vec1, acb_srcptr vec2, slong len, slong prec)"
arbcall"void _acb_vec_scalar_submul(acb_ptr res, acb_srcptr vec, slong len, const acb_t c, slong prec)"
arbcall"void _acb_vec_scalar_addmul(acb_ptr res, acb_srcptr vec, slong len, const acb_t c, slong prec)"
arbcall"void _acb_vec_scalar_mul(acb_ptr res, acb_srcptr vec, slong len, const acb_t c, slong prec)"
arbcall"void _acb_vec_scalar_mul_ui(acb_ptr res, acb_srcptr vec, slong len, ulong c, slong prec)"
arbcall"void _acb_vec_scalar_mul_2exp_si(acb_ptr res, acb_srcptr vec, slong len, slong c)"
arbcall"void _acb_vec_scalar_mul_onei(acb_ptr res, acb_srcptr vec, slong len)"
arbcall"void _acb_vec_scalar_div_ui(acb_ptr res, acb_srcptr vec, slong len, ulong c, slong prec)"
arbcall"void _acb_vec_scalar_div(acb_ptr res, acb_srcptr vec, slong len, const acb_t c, slong prec)"
arbcall"void _acb_vec_scalar_mul_arb(acb_ptr res, acb_srcptr vec, slong len, const arb_t c, slong prec)"
arbcall"void _acb_vec_scalar_div_arb(acb_ptr res, acb_srcptr vec, slong len, const arb_t c, slong prec)"
# arbcall"void _acb_vec_scalar_mul_fmpz(acb_ptr res, acb_srcptr vec, slong len, const fmpz_t c, slong prec)"
# arbcall"void _acb_vec_scalar_div_fmpz(acb_ptr res, acb_srcptr vec, slong len, const fmpz_t c, slong prec)"
arbcall"slong _acb_vec_bits(acb_srcptr vec, slong len)"
arbcall"void _acb_vec_set_powers(acb_ptr xs, const acb_t x, slong len, slong prec)"
arbcall"void _acb_vec_unit_roots(acb_ptr z, slong order, slong len, slong prec)"
# arbcall"void _acb_vec_add_error_arf_vec(acb_ptr res, arf_srcptr err, slong len)"
# arbcall"void _acb_vec_add_error_mag_vec(acb_ptr res, mag_srcptr err, slong len)"
arbcall"void _acb_vec_indeterminate(acb_ptr vec, slong len)"
arbcall"void _acb_vec_trim(acb_ptr res, acb_srcptr vec, slong len)"
# arbcall"int _acb_vec_get_unique_fmpz_vec(fmpz * res,  acb_srcptr vec, slong len)"
arbcall"void _acb_vec_sort_pretty(acb_ptr vec, slong len)"
