arbcall"void arb_mul_2exp_si(arb_t y, const arb_t x, slong e)"
arbcall"void arb_one(arb_t f)"
arbcall"void arb_pow_ui(arb_t y, const arb_t b, ulong e, slong prec)"
arbcall"void arb_fac_ui(arb_t z, ulong n, slong prec)"
arbcall"void arb_div(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_abs(arb_t y, const arb_t x)"
arbcall"void arb_add_error(arb_t x, const arb_t err)"
arbcall"void arb_add(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_sub(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_sub_si(arb_t z, const arb_t x, slong y, slong prec)"
arbcall"void arb_neg(arb_t y, const arb_t x)"
arbcall"void arb_mul(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"slong arb_rel_accuracy_bits(const arb_t x)"
arbcall"void arb_init(arb_t x)"
arbcall"void arb_clear(arb_t x)"
