arbcall"void arb_mul_2exp_si(arb_t y, const arb_t x, slong e)"
arbcall"void arb_one(arb_t f)"
arbcall"void arb_pow_ui(arb_t y, const arb_t b, ulong e, slong prec)"
arbcall"void arb_fac_ui(arb_t z, ulong n, slong prec)"
arbcall"void arb_div(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_abs(arb_t y, const arb_t x)"
arbcall"void arb_add_error(arb_t x, const arb_t err)"
arbcall"void arb_add(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_sub(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"void arb_sub_si(arb_t z, const arb_t x, slong y, slong prec)"
arbcall"void arb_neg(arb_t y, const arb_t x)"
arbcall"void arb_mul(arb_t z, const arb_t x, const arb_t y, slong prec)"
arbcall"slong arb_rel_accuracy_bits(const arb_t x)"
arbcall"void arb_init(arb_t x)"
arbcall"void arb_clear(arb_t x)"
arbcall"void arb_set(arb_t y, const arb_t x)"
arbcall"void arb_set_arf(arb_t y, const arf_t x)"
arbcall"void arb_set_si(arb_t y, slong x)"
arbcall"void arb_set_ui(arb_t y, ulong x)"
arbcall"void arb_set_d(arb_t y, double x)"
arbcall"int arb_set_str(arb_t res, const char * inp, slong prec)"
arbcall"void arb_const_pi(arb_t z, slong prec)"
arbcall"void arb_const_euler(arb_t z, slong prec)"
arbcall"void arb_const_e(arb_t z, slong prec)"
