arbcall"void arf_init(arf_t x)"
arbcall"void arf_clear(arf_t x)"
arbcall"void arf_init_set_ui(arf_t res, ulong x)"
arbcall"void arf_init_set_si(arf_t res, slong x)"
arbcall"void arf_set(arf_t res, const arf_t x)"
arbcall"void arf_set_ui(arf_t res, ulong x)"
arbcall"void arf_set_si(arf_t res, slong x)"
arbcall"void arf_set_mpfr(arf_t res, const mpfr_t x)"
arbcall"void arf_set_d(arf_t res, double x)"
arbcall"void arf_set_mag(arf_t res, const mag_t x)"
