arbcall"void arf_init(arf_t x)"
arbcall"void arf_clear(arf_t x)"
arbcall"void arf_init_set_ui(arf_t res, ulong x)"
arbcall"void arf_init_set_si(arf_t res, slong x)"
arbcall"void arf_set(arf_t res, const arf_t x)"
arbcall"void arf_set_ui(arf_t res, ulong x)"
arbcall"void arf_set_si(arf_t res, slong x)"
arbcall"void arf_set_mpfr(arf_t res, const mpfr_t x)"
arbcall"void arf_set_d(arf_t res, double x)"
arbcall"void arf_set_mag(arf_t res, const mag_t x)"
arbcall"int arf_is_zero(const arf_t x)"
arbcall"int arf_is_one(const arf_t x)"
arbcall"int arf_is_pos_inf(const arf_t x)"
arbcall"int arf_is_neg_inf(const arf_t x)"
arbcall"int arf_is_nan(const arf_t x)"
arbcall"int arf_is_inf(const arf_t x)"
arbcall"int arf_is_normal(const arf_t x)"
arbcall"int arf_is_special(const arf_t x)"
arbcall"int arf_is_finite(const arf_t x)"
arbcall"int arf_is_int(const arf_t x)"
arbcall"int arf_equal(const arf_t x, const arf_t y)"
arbcall"int arf_equal_si(const arf_t x, slong y)"
arbcall"int arf_cmp(const arf_t x, const arf_t y)"
arbcall"int arf_cmp_si(const arf_t x, slong y)"
arbcall"int arf_cmp_ui(const arf_t x, ulong y)"
arbcall"int arf_cmp_d(const arf_t x, double y)"
