arbcall"void mag_init(mag_t x)"
arbcall"void mag_clear(mag_t x)"
arbcall"void mag_init_set(mag_t res, const mag_t x)"
arbcall"void mag_init_set_arf(mag_t res, const arf_t x)"
arbcall"void mag_set(mag_t res, const mag_t x)"
arbcall"void mag_set_d(mag_t res, double x)"
arbcall"void mag_set_ui(mag_t res, ulong x)"
arbcall"void mag_const_pi(mag_t res)"
